### Create a new poem
POST http://localhost:7007/api/poem
Content-Type: application/json

{
  "title": "If You Forget Me",
  "poem": "I want you to know one thing...",
  "author": "Pablo Neruda",
  "type": "SONNET"
}

### Get all poems
GET http://localhost:7007/api/poem

### Get a specific poem by ID
GET http://localhost:7007/api/poem/1

### Update a poem by ID
PUT http://localhost:7007/api/poem/2
Content-Type: application/json

{
  "title": "If You Forget Me updated",
  "poem": "I want you to know one thing... updated",
  "author": "Pablo Neruda updated",
  "type": "SONNET"
}

### Delete a poem by ID
DELETE http://localhost:7007/api/poem/4